In [3]:
## Ali (AJ) Albaaj HW4
# NE 155

# Question 3 Matrix 2
import numpy as np
import scipy as sci
import matplotlib as plt

mat_2 = np.matrix([[4, -1, 2, 3], [0, 0, 7, -4], [0, 0, 6, 5], [0, 0, 0, 3]])
mat_2_b = np.array([20, -7, 4, 6])
print(mat_2, mat_2_b)
x_2 = np.linalg.tensorsolve(mat_2, mat_2_b)
print(x_2)

[[ 4 -1  2  3]
 [ 0  0  7 -4]
 [ 0  0  6  5]
 [ 0  0  0  3]] [20 -7  4  6]


LinAlgError: Singular matrix

In [4]:
# Question 3 Matrix 3

import numpy as np
import scipy as sci
import matplotlib as plt

mat_3 = np.matrix([[4, -1, 2, 3], [0, 0, 7, 0], [0, 0, 6, 5], [0, 0, 0, 3]])
mat_3_b = np.array([20, -7, 4, 6])
print(mat_3, mat_3_b)
x_2 = np.linalg.tensorsolve(mat_3, mat_3_b)
print(x_3)

[[ 4 -1  2  3]
 [ 0  0  7  0]
 [ 0  0  6  5]
 [ 0  0  0  3]] [20 -7  4  6]


LinAlgError: Singular matrix