In [5]:
## NE155 HW5 Ali (AJ) Albaaj
# Question 1

import scipy as sci
import numpy as np
import matplotlib.pyplot as plt

# creation of matrix for any n
n = 100
j = 1
A = np.zeros((n,n))
b = np.zeros((n,1))
A[0,0] = 2
A[0,1] = -1
while j < n-1:
    A[j,j-1] = -1
    A[j,j] = 2
    A[j,j+1] = -1
    b[j] = j
    j+=1
A[j,j-1] = -1
A[j,j] = 2
b[j] = j
    
# inverting matrix explicitly
Aprime = np.linalg.inv(A)
explicit = np.dot(Aprime, b)

# using built in numpy
builtin = np.linalg.solve(A,b)

# plotting on same chart including labels
x = np.arange(0,n)
plt.plot(x, explicit, 'bs', label='inverse')
plt.plot(x, builtin, 'r--', label='built-in')
plt.ylabel('calculated solution values')
plt.xlabel('x[j]')
plt.legend()
plt.show()
print(np.linalg.cond(A, 2))

4133.6429268


In [1]:
# Question 4

import numpy as np

def jacobi(A, b, N=5, x=None):
    
    # if no initial x, make a zero vector
    if x is None:
        x = np.zeros((N,1))
        
    D = np.diag(np.diag(A))
    R = A - D
    
    # intermediate matrices
    T = -np.dot(np.linalg.inv(D), R)
    C = np.dot(np.linalg.inv(D), b)
    
    # spectral radius
    rho, useless = np.linalg.eig(T)
    rho = max(np.absolute(rho))
    if rho >= 1:
        return 'does not converge'
    
    iter = -6/np.log10(rho) # what the correct number of iterations should be
    error = 0.000001
    # arbitrary old x is created to initialize loop
    oldx = np.zeros((N,1))
    oldx[0:5] = 100
    iter = 0
    
    # iterating until convergence
    while np.linalg.norm(x - oldx) > error:
        iter+=1
        oldx = x
        x = np.dot(T, oldx) + C
    return x, iter

def gauss(A, b, N=5, x=None):
    
    if x is None:
        x = np.zeros((N,1))
        
    D = np.diag(np.diag(A))
    L = np.tril(A)
    U = np.triu(A) - D
    
    # intermediate matrices
    T = np.dot(np.linalg.inv(L), -U)
    C = np.dot(np.linalg.inv(L), b)
    
    # spectral radius
    rho, useless = np.linalg.eig(T)
    rho = max(np.absolute(rho))
    if rho >= 1:
        return 'does not converge'
    
    iter = -6/np.log10(rho) # what the correct number of iterations should be
    error = 0.000001
    oldx = np.zeros((N,1))
    oldx[0:5] = 100
    iter = 0
    
    # iterating until convergence
    while np.linalg.norm(x - oldx) > error:
        iter+=1
        oldx = x
        x = np.dot(T, oldx) + C
    return x, iter

def SOR(A, b, N=5, x=None, omega=1.1):
    
    if x is None:
        x = np.zeros((N,1))
    
    D = np.diag(np.diag(A))
    L = np.tril(A) - D
    U = A - L - D
    
    # intermediate matrices
    T = np.linalg.inv(D + omega*L)
    S = (1-omega)*D - omega*U
    P = np.dot(T,S)
    C = np.dot(T, omega*b)
    
    # spectral radius
    rho, useless = np.linalg.eig(P)
    rho = max(np.absolute(rho))
    if rho >= 1:
        return 'does not converge'
    
    iter = -6/np.log10(rho) # what the correct number of iterations should be
    error = 0.000001
    oldx = np.zeros((N,1))
    oldx[0:5] = 100
    iter = 0
    
    # iterating until convergence
    while np.linalg.norm(x - oldx) > error:
        iter+=1
        oldx = x
        x = np.dot(P, oldx) + C
    return x, iter

init = np.zeros((5,1))
init[0:5] = 100
A = np.matrix('4 -1 0 0 0; -1 4 -1 0 0; 0 -1 4 -1 0; 0 0 -1 4 -1; 0 0 0 -1 4')
jacoResults, jacoIter = jacobi(A, init)
gaussResults, gaussIter = gauss(A, init)
SORResults, SORIter = SOR(A, init)
print(jacoResults)
print(gaussResults)
print(SORResults)
print(jacoIter, gaussIter, SORIter)

[[ 36.53846142]
 [ 46.15384594]
 [ 48.07692284]
 [ 46.15384594]
 [ 36.53846142]]
[[ 36.53846142]
 [ 46.15384606]
 [ 48.07692303]
 [ 46.15384614]
 [ 36.53846153]]
[[ 36.53846919]
 [ 46.1538498 ]
 [ 48.07692421]
 [ 46.15384677]
 [ 36.53846134]]
23 13 8


C:\Users\MITMobile\Anaconda3\lib\site-packages\ipykernel\__main__.py:96: RuntimeWarning: divide by zero encountered in double_scalars


In [9]:
# Question 5

import numpy as np

def jacobi(A, b, N=5, x=None):
    
    if x is None:
        x = np.zeros((N,1))
        
    D = np.diag(np.diag(A))
    R = A - D
    
    # intermediate matrices
    T = -np.dot(np.linalg.inv(D), R)
    C = np.dot(np.linalg.inv(D), b)
    
    # spectral radius
    rho, useless = np.linalg.eig(T)
    rho = max(np.absolute(rho))
    if rho >= 1:
        return 'does not converge'
    
    iter = -8/np.log10(rho) # what the correct number of iterations should be
    error = 0.00000001
    oldx = np.zeros((N,1))
    oldx[0:5] = 100
    iter = 0
    
    # iterating until convergence
    while (np.linalg.norm(x - oldx) / np.linalg.norm(x)) > error:
        iter+=1
        oldx = x
        x = np.dot(T, oldx) + C
    return x, iter

def gauss(A, b, N=5, x=None):
    
    if x is None:
        x = np.zeros((N,1))
        
    D = np.diag(np.diag(A))
    L = np.tril(A)
    U = np.triu(A) - D
    
    # intermediate matrices
    T = np.dot(np.linalg.inv(L), -U)
    C = np.dot(np.linalg.inv(L), b)
    
    # spectral radius
    rho, useless = np.linalg.eig(T)
    rho = max(np.absolute(rho))
    if rho >= 1:
        return 'does not converge'
    
    iter = -8/np.log10(rho) # what the correct number of iterations should be
    error = 0.00000001
    oldx = np.zeros((N,1))
    oldx[0:5] = 100
    iter = 0
    
    # iterating until convergence
    while (np.linalg.norm(x - oldx) / np.linalg.norm(x)) > error:
        iter+=1
        oldx = x
        x = np.dot(T, oldx) + C
    return x, iter

def SOR(A, b, omega, N=5, x=None):
    
    if x is None:
        x = np.zeros((N,1))
    
    D = np.diag(np.diag(A))
    L = np.tril(A) - D
    U = A - L - D
    
    # intermediate matrices
    T = np.linalg.inv(D + omega*L)
    S = (1-omega)*D - omega*U
    P = np.dot(T,S)
    C = np.dot(T, omega*b)
    
    # spectral radius
    rho, useless = np.linalg.eig(P)
    rho = max(np.absolute(rho))
    if rho >= 1:
        return 0
    
    iter = -8/np.log10(rho) # what the correct number of iterations should be
    error = 0.00000001
    oldx = np.zeros((N,1))
    oldx[0:5] = 100
    iter = 0
    
    # iterating until convergence
    while (np.linalg.norm(x - oldx) / np.linalg.norm(x)) > error:
        iter+=1
        oldx = x
        x = np.dot(P, oldx) + C
    return iter

init = np.zeros((5,1))
init[0:5] = 100
A = np.matrix('4 -1 0 0 0; -1 4 -1 0 0; 0 -1 4 -1 0; 0 0 -1 4 -1; 0 0 0 -1 4')
jacoResults, jacoIter = jacobi(A, init)
gaussResults, gaussIter = gauss(A, init)
SORIter = SOR(A, init, 1.052)
print(jacoIter, gaussIter, SORIter)
print(jacoResults, gaussResults)

omegaChain = np.arange(1,2,0.001)
# had to remove the actual results due to inefficiencies in the code but I did check to make sure the correct answer was calculated
omegaIter = np.zeros(omegaChain.size)
for i in np.arange(1,2,0.001):
    omegaIter[i] = SOR(A, init, i)


23 13 10
[[ 36.53846142]
 [ 46.15384594]
 [ 48.07692284]
 [ 46.15384594]
 [ 36.53846142]] [[ 36.53846142]
 [ 46.15384606]
 [ 48.07692303]
 [ 46.15384614]
 [ 36.53846153]]


C:\Users\MITMobile\Anaconda3\lib\site-packages\ipykernel\__main__.py:30: RuntimeWarning: divide by zero encountered in double_scalars
C:\Users\MITMobile\Anaconda3\lib\site-packages\ipykernel\__main__.py:62: RuntimeWarning: divide by zero encountered in double_scalars
C:\Users\MITMobile\Anaconda3\lib\site-packages\ipykernel\__main__.py:96: RuntimeWarning: divide by zero encountered in double_scalars
C:\Users\MITMobile\Anaconda3\lib\site-packages\ipykernel\__main__.py:115: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
